# Generated by Django 5.0.6 on 2024-07-10 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_alter_advert_user'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='advert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='ads.advert'),
            preserve_default=False,
        ),
    ]
