# Generated by Django 5.0.6 on 2024-07-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_rename_ads_adverts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverts',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
