# Generated by Django 5.0.6 on 2024-07-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_rename_adverts_advert_rename_date_advert_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
