# Generated by Django 5.0.6 on 2024-07-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_advert_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.ImageField(null=True, upload_to='ads/images/'),
        ),
    ]
