# Generated by Django 5.0.6 on 2024-07-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_advert_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='advert',
            name='topic',
            field=models.CharField(choices=[('cars', 'Машины'), ('real_estate', 'Недвижимость'), ('appliances', 'Бытовая техника'), ('clothing', 'Одежда'), ('other', 'Другое')], max_length=30),
        ),
    ]
